require('dotenv').config();

const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');
const express = require('express');
const favicon = require('serve-favicon');
const hbs = require('hbs');
const mongoose = require('mongoose');
const logger = require('morgan');
const path = require('path');

const app_name = require('./package.json').name;
const debug = require('debug')(
  `${app_name}:${path.basename(__filename).split('.')[0]}`
);

const app = express();

// require database configuration
require('./config/connectDb');

const dbOptions = {
  useCreateIndex: true,
  useNewUrlParser: true,
  useUnifiedTopology: true,
};

async function connectDb() {
  try {
      const connection = await mongoose.connect(
      'mongodb://localhost/express-cinema-dev',
      {
        useCreateIndex: true,
        useNewUrlParser: true,
        useUnifiedTopology: true,
      }
      );
      console.log("connected to mongo db");
  } catch (err) {
      console.error(err);
  }
}
connectDb()

// Middleware Setup
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());

// Express View engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'hbs');
app.use(express.static(path.join(__dirname, 'public')));
app.use(favicon(path.join(__dirname, 'public', 'images', 'favicon.ico')));

// default value for title local
app.locals.title = 'Express - Generated by Monica';

const index = require('./routes');
app.use('/', index);

const { 
  getMovies, 
  getMovie,
} = require('./controllers/movies.controllers');

//Ruta a movies
app.get('/movies', getMovies)
//Ruta a movie-detail
app.get('/movies/:movieId', getMovie)

// const moviesRoute = require('./routes/movies.route')
// app.use('/', moviesRoute)
//app.use('/movies', moviesRoute)

module.exports = app;
